### ISSUE TITLE
get "/oauth/callback" raises NoMethodError - undefined method `get_result' (gem version only)

### ISSUE THREAD

**Issue by patbl** [turadg/pocket-ruby#6]
What I did:
- ran `gem install pocket-ruby`
- downloaded `demo-server.rb`
- changed third line to `require pocket`
- changed the `consumer_key` to my own
- ran `ruby demo-server.rb`

When I click on the "Connect with Pocket" link, I get the following error:

```
OAUTH CALLBACK
request.url: http://localhost:4567/oauth/callback
request.body:
NoMethodError - undefined method `get_result' for Pocket:Module:
        /home/pat/.rvm/gems/ruby-2.1.0/gems/pocket-ruby-0.0.4/lib/pocket.rb:18:in `method_missing'
        demo-server.rb:45:in `block in <main>'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1593:in `call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1593:in `block in compile!'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:957:in `[]'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:957:in `block (3 levels) in route!'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:976:in `route_eval'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:957:in `block (2 levels) in route!'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:997:in `block in process_route'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:995:in `catch'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:995:in `process_route'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:955:in `block in route!'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:954:in `each'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:954:in `route!'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1067:in `block in dispatch!'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `block in invoke'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `catch'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `invoke'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1064:in `dispatch!'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:889:in `block in call!'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `block in invoke'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `catch'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `invoke'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:889:in `call!'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:877:in `call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/rack-protection-1.5.1/lib/rack/protection/xss_header.rb:18:in `call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/rack-protection-1.5.1/lib/rack/protection/base.rb:50:in `call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/rack-protection-1.5.1/lib/rack/protection/base.rb:50:in `call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/rack-protection-1.5.1/lib/rack/protection/path_traversal.rb:16:in `call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/rack-protection-1.5.1/lib/rack/protection/json_csrf.rb:18:in `call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/rack-protection-1.5.1/lib/rack/protection/base.rb:50:in `call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/rack-protection-1.5.1/lib/rack/protection/base.rb:50:in `call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/rack-protection-1.5.1/lib/rack/protection/frame_options.rb:31:in `call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/logger.rb:15:in `call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in `call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:217:in `call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:210:in `call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/show_exceptions.rb:21:in `call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:180:in `call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:2004:in `call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1469:in `block in call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1778:in `synchronize'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1469:in `call'
        /home/pat/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
        /home/pat/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
        /home/pat/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
        /home/pat/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
localhost - - [09/Feb/2014:20:20:27 AKST] "GET /oauth/callback HTTP/1.1" 500 151082
http://localhost:4567/ -> /oauth/callback
```

The `git clone`'d version works fine. I realize I'm probably doing something wrong.

**Comment by jasonngpt** [comment]
hey @patbl 

i just tried it out with rbenv for 1.9.3 and 2.1.0, and gem install pocket-ruby.. 

both works fine as per expected, Connect with Pocket redirects to the Pocket login page..

The noticeable difference is rvm vs rbenv.. i am not too familiar with rvm.. anybody using rvm to try it out?

**Comment by betamax** [comment]
Instead of `get_result` it should be `get_access_token` - or at least, that works. I've submitted a pull request (above) that fixes the demo server code.

**Comment by jasonngpt** [comment]
@betamax ah good find.. the gem is of an older version than the git version.. that's why the `get_result` is missing.. your PR should fix the issue here.. will comment over there.. will close this issue when the PR is merged.. thanks!
